services:
  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./imdb_db:/imdb_data

  loader:
    build: .
    env_file:
      - .env
    volumes:
      - ./imdb_db:/imdb_data
    depends_on:
      - db